"""empty message

Revision ID: 669df08b42af
Revises: 
Create Date: 2019-12-27 23:09:31.792042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '669df08b42af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('comment', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'comment')
    # ### end Alembic commands ###
